apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: ace-ecollection-prod1
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: ace-ecollection-prod1
  spec:
   containers:
    - name: ace-ecollection-prod1
      image: milindlasurve1/cateina:ace24122019-new-7600-6
      ports:
       - containerPort: 7600
       - containerPort: 1414
       - containerPort: 7800
       - containerPort: 7843
       - containerPort: 9157
       - containerPort: 9443
       - containerPort: 9483
      command: ["/bin/sh"]
      args: ["-c", "echo test > /tmp/milind.txt"]
      env:
       - name: LICENSE
         value: accept
       - name: MQ_QMGR_NAME
         value: LQM.IXC.prod
      volumeMounts:
        - mountPath: /home/aceuser/build
          name: aceuser
      restartPolicy: Always
   volumes:
       - name: aceuser
         persistentVolumeClaim:
          claimName: ace-ecollection-sit
---
apiVersion: v1
kind: Service
metadata:
 name: ace-ecollection-prod1
spec:
 selector:
   app: ace-ecollection-prod1
 ports:
  - name: ace-ecollection-prod1
    port: 7600
    targatePort:
---
apiVersion: v1
kind: Route
metadata:
  name: ace-ecollection-prod1
spec:
  host: ace-ecollection-prod1-testing.28122019.13.71.81.159.nip.io
  path: "/" 
  to:
    kind: Service
    name: ace-ecollection-prod1
